// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtEoXAAUJMQVkO_NgEQwhTA6_WcqQ2-70',
    appId: '1:155280912764:web:af6b5c706a0fd47d7ff4f9',
    messagingSenderId: '155280912764',
    projectId: 'bmi22-1c69d',
    authDomain: 'bmi22-1c69d.firebaseapp.com',
    storageBucket: 'bmi22-1c69d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB249TKjKWDZ0XLJ-qjjbPUVe8yNXulJN8',
    appId: '1:155280912764:android:2674aeed441f6e297ff4f9',
    messagingSenderId: '155280912764',
    projectId: 'bmi22-1c69d',
    storageBucket: 'bmi22-1c69d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2qRbM3hc_ck35nTrHBRoeQSYpRGpEdyU',
    appId: '1:155280912764:ios:5275daa64cbb15d47ff4f9',
    messagingSenderId: '155280912764',
    projectId: 'bmi22-1c69d',
    storageBucket: 'bmi22-1c69d.appspot.com',
    iosBundleId: 'com.example.caloriescounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2qRbM3hc_ck35nTrHBRoeQSYpRGpEdyU',
    appId: '1:155280912764:ios:5275daa64cbb15d47ff4f9',
    messagingSenderId: '155280912764',
    projectId: 'bmi22-1c69d',
    storageBucket: 'bmi22-1c69d.appspot.com',
    iosBundleId: 'com.example.caloriescounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtEoXAAUJMQVkO_NgEQwhTA6_WcqQ2-70',
    appId: '1:155280912764:web:74ae62675b3b07ef7ff4f9',
    messagingSenderId: '155280912764',
    projectId: 'bmi22-1c69d',
    authDomain: 'bmi22-1c69d.firebaseapp.com',
    storageBucket: 'bmi22-1c69d.appspot.com',
  );
}
